### ISSUE TITLE
There should be a discussion on the virus flags raised by announcementwindow.exe

### ISSUE THREAD

**Issue by xylax11** [NuAoA/AnnouncementWindow#14]
https://www.virustotal.com/en/file/b5a1da567ba815614067b60d8272f4f5062f389045c29b5bfeeb734c980169cd/analysis/

**Comment by lethosor** [comment]
Chances are pretty good that those are false positives, given that PyInstaller-built executables have run into false positives in the past and most of those scans returned negative results. If you really want to be safe, you can install Python and run it from source (or build your own executable and compare its AV scan results).

**Comment by xylax11** [comment]
All I could find on the subject was [this single result](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22AnnoucementWindow.exe%22). Hopfuly Google will index this page so that others can be at ease.

**Comment by NuAoA** [comment]
Yea, the code is compiled with pyinstaller straight from the source. If you don't trust the .exe you can just get python and run the source code directly if you wish (as lethosor said). If you want to compile it yourself, heres the .spec file I use to pack the .exe. I use 32 bit python 2.7.10 when I compile.

```
# -*- mode: python -*-
import shutil, os

block_cipher = None

a = Analysis(['run.py'],
             pathex=['D:\\workspace\\Announcement Window\\AnnouncementWindow'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             win_no_prefer_redirects=None,
             win_private_assemblies=None,
             cipher=block_cipher)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='AnnouncementWindow',
          debug=False,
          strip=None,
          upx=True,
          console=False,
          icon='Data\\favicon.ico',
          )

os.makedirs('dist/Data')
shutil.copyfile('Data/favicon.ico', 'dist/Data/favicon.ico')
shutil.copyfile('filters.txt', 'dist/filters.txt')
shutil.copyfile('Data/filters.dat', 'dist/Data/filters.dat')
shutil.copyfile('readme.md', 'dist/readme.md')
```

**Comment by txtsd** [comment]
@NuAoA You should include the spec file in the repo so linux users can have an executable too :)

**Comment by NuAoA** [comment]
Huh, I didn't even know you could do that. I guess i'll remove it from .gitignore

**Comment by xylax11** [comment]
+1
